"use strict";
class Customer {
    //constructors - use constructor keyword - must use "this"
    constructor(theFirst, theLast) {
        this._firstName = theFirst;
        this._lastName = theLast;
    }
    //get/set accessors 
    get firstName() {
        return this._firstName;
    }
    //no return type (not even void)
    set firstName(value) {
        this._firstName = value;
    }
    //generated by IDE
    get lastName() {
        return this._lastName;
    }
    set lastName(value) {
        this._lastName = value;
    }
}
let myCustomer = new Customer('Martin', 'Lawrence');
myCustomer.firstName = 'Susan';
myCustomer.lastName = 'Public';
console.log(myCustomer.firstName);
console.log(myCustomer.lastName);
